-- AlterTable
ALTER TABLE "Badge" ADD COLUMN     "dateMinted" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Entity" ADD COLUMN     "dateRegistered" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "PermissionToken" ADD COLUMN     "dateMinted" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
