/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IPermissionTokenFactory,
  IPermissionTokenFactoryInterface,
} from "../IPermissionTokenFactory";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "entityName",
        type: "string",
      },
      {
        indexed: false,
        internalType: "address",
        name: "entityAddress",
        type: "address",
      },
    ],
    name: "PermissionTokenDeployed",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_entityName",
        type: "string",
      },
    ],
    name: "createPermissionToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IPermissionTokenFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IPermissionTokenFactoryInterface {
    return new utils.Interface(_abi) as IPermissionTokenFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPermissionTokenFactory {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IPermissionTokenFactory;
  }
}
