/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IPermissionToken,
  IPermissionTokenInterface,
} from "../IPermissionToken";

const _abi = [
  {
    inputs: [],
    name: "getEntityAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getPermStatusForUser",
    outputs: [
      {
        internalType: "enum PermLevel",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
      {
        internalType: "enum PermLevel",
        name: "level",
        type: "uint8",
      },
      {
        internalType: "string",
        name: "tokenURI",
        type: "string",
      },
    ],
    name: "mintAsEntity",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
];

export class IPermissionToken__factory {
  static readonly abi = _abi;
  static createInterface(): IPermissionTokenInterface {
    return new utils.Interface(_abi) as IPermissionTokenInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPermissionToken {
    return new Contract(address, _abi, signerOrProvider) as IPermissionToken;
  }
}
