/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface BadgePriceCalculatorInterface extends ethers.utils.Interface {
  functions: {
    "baseBadgePrice()": FunctionFragment;
    "calculateBadgePrice(uint256)": FunctionFragment;
    "levelMultiplierX1000()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "baseBadgePrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateBadgePrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "levelMultiplierX1000",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "baseBadgePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateBadgePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "levelMultiplierX1000",
    data: BytesLike
  ): Result;

  events: {};
}

export class BadgePriceCalculator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: BadgePriceCalculatorInterface;

  functions: {
    baseBadgePrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    calculateBadgePrice(
      level: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    levelMultiplierX1000(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  baseBadgePrice(overrides?: CallOverrides): Promise<BigNumber>;

  calculateBadgePrice(
    level: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  levelMultiplierX1000(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    baseBadgePrice(overrides?: CallOverrides): Promise<BigNumber>;

    calculateBadgePrice(
      level: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    levelMultiplierX1000(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    baseBadgePrice(overrides?: CallOverrides): Promise<BigNumber>;

    calculateBadgePrice(
      level: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    levelMultiplierX1000(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    baseBadgePrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    calculateBadgePrice(
      level: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    levelMultiplierX1000(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
