/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IBadgeRecoveryOracleInterface extends ethers.utils.Interface {
  functions: {
    "getRecoveryAddress(address)": FunctionFragment;
    "setRecoveryAddress(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getRecoveryAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setRecoveryAddress",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getRecoveryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRecoveryAddress",
    data: BytesLike
  ): Result;

  events: {
    "RecoveryAddressSet(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "RecoveryAddressSet"): EventFragment;
}

export type RecoveryAddressSetEvent = TypedEvent<
  [string, string] & { initialAddress: string; recoveryAddress: string }
>;

export class IBadgeRecoveryOracle extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IBadgeRecoveryOracleInterface;

  functions: {
    getRecoveryAddress(
      _address: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    setRecoveryAddress(
      _recoveryAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getRecoveryAddress(
    _address: string,
    overrides?: CallOverrides
  ): Promise<string>;

  setRecoveryAddress(
    _recoveryAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getRecoveryAddress(
      _address: string,
      overrides?: CallOverrides
    ): Promise<string>;

    setRecoveryAddress(
      _recoveryAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "RecoveryAddressSet(address,address)"(
      initialAddress?: null,
      recoveryAddress?: null
    ): TypedEventFilter<
      [string, string],
      { initialAddress: string; recoveryAddress: string }
    >;

    RecoveryAddressSet(
      initialAddress?: null,
      recoveryAddress?: null
    ): TypedEventFilter<
      [string, string],
      { initialAddress: string; recoveryAddress: string }
    >;
  };

  estimateGas: {
    getRecoveryAddress(
      _address: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setRecoveryAddress(
      _recoveryAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getRecoveryAddress(
      _address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setRecoveryAddress(
      _recoveryAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
