/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IBadgeTokenInterface extends ethers.utils.Interface {
  functions: {
    "burn(uint256,bool)": FunctionFragment;
    "getDemeritPoints()": FunctionFragment;
    "getEntity()": FunctionFragment;
    "mintBadge(address,uint256,string)": FunctionFragment;
    "setNewEntity(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "burn",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getDemeritPoints",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getEntity", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "mintBadge",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setNewEntity",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDemeritPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEntity", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mintBadge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setNewEntity",
    data: BytesLike
  ): Result;

  events: {
    "BadgeBurned(address,bool)": EventFragment;
    "BadgeMinted(address,uint256,uint256,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BadgeBurned"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BadgeMinted"): EventFragment;
}

export type BadgeBurnedEvent = TypedEvent<
  [string, boolean] & { entityAddress: string; withPrejudice: boolean }
>;

export type BadgeMintedEvent = TypedEvent<
  [string, BigNumber, BigNumber, string] & {
    entity: string;
    tokenId: BigNumber;
    level: BigNumber;
    tokenURI: string;
  }
>;

export class IBadgeToken extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IBadgeTokenInterface;

  functions: {
    burn(
      tokenId: BigNumberish,
      withPrejudice: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getDemeritPoints(overrides?: CallOverrides): Promise<[BigNumber]>;

    getEntity(overrides?: CallOverrides): Promise<[string]>;

    mintBadge(
      _to: string,
      level: BigNumberish,
      _tokenURI: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setNewEntity(
      _entity: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  burn(
    tokenId: BigNumberish,
    withPrejudice: boolean,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getDemeritPoints(overrides?: CallOverrides): Promise<BigNumber>;

  getEntity(overrides?: CallOverrides): Promise<string>;

  mintBadge(
    _to: string,
    level: BigNumberish,
    _tokenURI: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setNewEntity(
    _entity: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    burn(
      tokenId: BigNumberish,
      withPrejudice: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    getDemeritPoints(overrides?: CallOverrides): Promise<BigNumber>;

    getEntity(overrides?: CallOverrides): Promise<string>;

    mintBadge(
      _to: string,
      level: BigNumberish,
      _tokenURI: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setNewEntity(_entity: string, overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "BadgeBurned(address,bool)"(
      entityAddress?: null,
      withPrejudice?: null
    ): TypedEventFilter<
      [string, boolean],
      { entityAddress: string; withPrejudice: boolean }
    >;

    BadgeBurned(
      entityAddress?: null,
      withPrejudice?: null
    ): TypedEventFilter<
      [string, boolean],
      { entityAddress: string; withPrejudice: boolean }
    >;

    "BadgeMinted(address,uint256,uint256,string)"(
      entity?: null,
      tokenId?: null,
      level?: null,
      tokenURI?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, string],
      { entity: string; tokenId: BigNumber; level: BigNumber; tokenURI: string }
    >;

    BadgeMinted(
      entity?: null,
      tokenId?: null,
      level?: null,
      tokenURI?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, string],
      { entity: string; tokenId: BigNumber; level: BigNumber; tokenURI: string }
    >;
  };

  estimateGas: {
    burn(
      tokenId: BigNumberish,
      withPrejudice: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getDemeritPoints(overrides?: CallOverrides): Promise<BigNumber>;

    getEntity(overrides?: CallOverrides): Promise<BigNumber>;

    mintBadge(
      _to: string,
      level: BigNumberish,
      _tokenURI: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setNewEntity(
      _entity: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    burn(
      tokenId: BigNumberish,
      withPrejudice: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getDemeritPoints(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getEntity(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mintBadge(
      _to: string,
      level: BigNumberish,
      _tokenURI: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setNewEntity(
      _entity: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
