/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IBadgeXPInterface extends ethers.utils.Interface {
  functions: {
    "burn(uint256,address,address)": FunctionFragment;
    "getXPForBadgeContractToRecipient(address,address)": FunctionFragment;
    "mint(uint256,address,address)": FunctionFragment;
    "resetXP(uint256,address,address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "burn",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getXPForBadgeContractToRecipient",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "resetXP",
    values: [BigNumberish, string, string, string]
  ): string;

  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getXPForBadgeContractToRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "resetXP", data: BytesLike): Result;

  events: {};
}

export class IBadgeXP extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IBadgeXPInterface;

  functions: {
    burn(
      amount: BigNumberish,
      recipient: string,
      registry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getXPForBadgeContractToRecipient(
      badgeContract: string,
      recipient: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    mint(
      level: BigNumberish,
      recipient: string,
      registry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    resetXP(
      amount: BigNumberish,
      from: string,
      to: string,
      registry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  burn(
    amount: BigNumberish,
    recipient: string,
    registry: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getXPForBadgeContractToRecipient(
    badgeContract: string,
    recipient: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  mint(
    level: BigNumberish,
    recipient: string,
    registry: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  resetXP(
    amount: BigNumberish,
    from: string,
    to: string,
    registry: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    burn(
      amount: BigNumberish,
      recipient: string,
      registry: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getXPForBadgeContractToRecipient(
      badgeContract: string,
      recipient: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    mint(
      level: BigNumberish,
      recipient: string,
      registry: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    resetXP(
      amount: BigNumberish,
      from: string,
      to: string,
      registry: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    burn(
      amount: BigNumberish,
      recipient: string,
      registry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getXPForBadgeContractToRecipient(
      badgeContract: string,
      recipient: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    mint(
      level: BigNumberish,
      recipient: string,
      registry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    resetXP(
      amount: BigNumberish,
      from: string,
      to: string,
      registry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    burn(
      amount: BigNumberish,
      recipient: string,
      registry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getXPForBadgeContractToRecipient(
      badgeContract: string,
      recipient: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    mint(
      level: BigNumberish,
      recipient: string,
      registry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    resetXP(
      amount: BigNumberish,
      from: string,
      to: string,
      registry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
