/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IBadgeRegistryInterface extends ethers.utils.Interface {
  functions: {
    "getBadgePrice(uint256)": FunctionFragment;
    "getBadgeTokenFactory()": FunctionFragment;
    "getBadgeXPToken()": FunctionFragment;
    "getBaseMinimumStake()": FunctionFragment;
    "getEntityFactory()": FunctionFragment;
    "getPermissionTokenFactory()": FunctionFragment;
    "getRecoveryOracle()": FunctionFragment;
    "getSafe()": FunctionFragment;
    "isRegistered(address)": FunctionFragment;
    "isRegistryCertified(address)": FunctionFragment;
    "setTokenReverseRecords(address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getBadgePrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBadgeTokenFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBadgeXPToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBaseMinimumStake",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEntityFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPermissionTokenFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRecoveryOracle",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getSafe", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistryCertified",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenReverseRecords",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getBadgePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBadgeTokenFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBadgeXPToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBaseMinimumStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntityFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPermissionTokenFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecoveryOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSafe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegistryCertified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenReverseRecords",
    data: BytesLike
  ): Result;

  events: {};
}

export class IBadgeRegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IBadgeRegistryInterface;

  functions: {
    getBadgePrice(
      level: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getBadgeTokenFactory(overrides?: CallOverrides): Promise<[string]>;

    getBadgeXPToken(overrides?: CallOverrides): Promise<[string]>;

    getBaseMinimumStake(overrides?: CallOverrides): Promise<[BigNumber]>;

    getEntityFactory(overrides?: CallOverrides): Promise<[string]>;

    getPermissionTokenFactory(overrides?: CallOverrides): Promise<[string]>;

    getRecoveryOracle(overrides?: CallOverrides): Promise<[string]>;

    getSafe(overrides?: CallOverrides): Promise<[string]>;

    isRegistered(addr: string, overrides?: CallOverrides): Promise<[boolean]>;

    isRegistryCertified(
      _registry: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    setTokenReverseRecords(
      perm: string,
      badge: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getBadgePrice(
    level: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getBadgeTokenFactory(overrides?: CallOverrides): Promise<string>;

  getBadgeXPToken(overrides?: CallOverrides): Promise<string>;

  getBaseMinimumStake(overrides?: CallOverrides): Promise<BigNumber>;

  getEntityFactory(overrides?: CallOverrides): Promise<string>;

  getPermissionTokenFactory(overrides?: CallOverrides): Promise<string>;

  getRecoveryOracle(overrides?: CallOverrides): Promise<string>;

  getSafe(overrides?: CallOverrides): Promise<string>;

  isRegistered(addr: string, overrides?: CallOverrides): Promise<boolean>;

  isRegistryCertified(
    _registry: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  setTokenReverseRecords(
    perm: string,
    badge: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getBadgePrice(
      level: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBadgeTokenFactory(overrides?: CallOverrides): Promise<string>;

    getBadgeXPToken(overrides?: CallOverrides): Promise<string>;

    getBaseMinimumStake(overrides?: CallOverrides): Promise<BigNumber>;

    getEntityFactory(overrides?: CallOverrides): Promise<string>;

    getPermissionTokenFactory(overrides?: CallOverrides): Promise<string>;

    getRecoveryOracle(overrides?: CallOverrides): Promise<string>;

    getSafe(overrides?: CallOverrides): Promise<string>;

    isRegistered(addr: string, overrides?: CallOverrides): Promise<boolean>;

    isRegistryCertified(
      _registry: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    setTokenReverseRecords(
      perm: string,
      badge: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getBadgePrice(
      level: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBadgeTokenFactory(overrides?: CallOverrides): Promise<BigNumber>;

    getBadgeXPToken(overrides?: CallOverrides): Promise<BigNumber>;

    getBaseMinimumStake(overrides?: CallOverrides): Promise<BigNumber>;

    getEntityFactory(overrides?: CallOverrides): Promise<BigNumber>;

    getPermissionTokenFactory(overrides?: CallOverrides): Promise<BigNumber>;

    getRecoveryOracle(overrides?: CallOverrides): Promise<BigNumber>;

    getSafe(overrides?: CallOverrides): Promise<BigNumber>;

    isRegistered(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

    isRegistryCertified(
      _registry: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setTokenReverseRecords(
      perm: string,
      badge: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getBadgePrice(
      level: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBadgeTokenFactory(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBadgeXPToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getBaseMinimumStake(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEntityFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPermissionTokenFactory(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRecoveryOracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getSafe(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isRegistered(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isRegistryCertified(
      _registry: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setTokenReverseRecords(
      perm: string,
      badge: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
