/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IEntityInterface extends ethers.utils.Interface {
  functions: {
    "getBadgeRegistry()": FunctionFragment;
    "getBadgeToken()": FunctionFragment;
    "getPermissionToken()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getBadgeRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBadgeToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPermissionToken",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getBadgeRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBadgeToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPermissionToken",
    data: BytesLike
  ): Result;

  events: {};
}

export class IEntity extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IEntityInterface;

  functions: {
    getBadgeRegistry(overrides?: CallOverrides): Promise<[string]>;

    getBadgeToken(overrides?: CallOverrides): Promise<[string]>;

    getPermissionToken(overrides?: CallOverrides): Promise<[string]>;
  };

  getBadgeRegistry(overrides?: CallOverrides): Promise<string>;

  getBadgeToken(overrides?: CallOverrides): Promise<string>;

  getPermissionToken(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    getBadgeRegistry(overrides?: CallOverrides): Promise<string>;

    getBadgeToken(overrides?: CallOverrides): Promise<string>;

    getPermissionToken(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getBadgeRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    getBadgeToken(overrides?: CallOverrides): Promise<BigNumber>;

    getPermissionToken(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getBadgeRegistry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getBadgeToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPermissionToken(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
